=== sylvaingir/j8583/src/main/resources/com/solab/iso8583/parse/j8583.dtd
<!ELEMENT j8583-config ( header*, template*, parse* ) >

<!ELEMENT header ( #PCDATA ) >
<!ATTLIST header type NMTOKEN #REQUIRED >
<!ATTLIST header ref NMTOKEN #IMPLIED >
<!ATTLIST header binary ( true | false ) #IMPLIED >

<!ELEMENT template ( field* ) >
<!ATTLIST template type NMTOKEN #REQUIRED >
<!ATTLIST template extends NMTOKEN #IMPLIED >

<!ELEMENT parse ( field* ) >
<!ATTLIST parse type NMTOKEN #REQUIRED >
<!ATTLIST parse extends NMTOKEN #IMPLIED >

<!ELEMENT field ( #PCDATA|field )* >
<!ATTLIST field num NMTOKEN #REQUIRED >
<!ATTLIST field length NMTOKEN #IMPLIED >
<!ATTLIST field type ( ALPHA | NUMERIC | AMOUNT | DATE4 | DATE6 | DATE10 | DATE12 | DATE14 | DATE_EXP | TIME | LLVAR | LLLVAR | LLLLVAR | BINARY | LLBIN | LLLBIN | LLLLBIN | LLBCDBIN | LLLBCDBIN | LLLLBCDBIN | exclude) #REQUIRED >

=== sylvaingir/j8583/src/test/resources/config800.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE j8583-config PUBLIC "-//J8583//DTD CONFIG 1.0//EN" "http://j8583.sourceforge.net/j8583.dtd">
<j8583-config>

    <template type="0800">
        <field num="7" type="DATE10">1201145101</field>
        <field num="11" type="NUMERIC" length="6">562040</field>
        <field num="70" type="NUMERIC" length="3">270</field>
    </template>


    <parse type="0810">
        <field num="7" type="DATE10"/>
        <field num="11" type="NUMERIC" length="6"/>
        <field num="37" type="ALPHA" length="12"/>
        <field num="39" type="NUMERIC" length="2"/>
        <field num="70" type="NUMERIC" length="3"/>
    </parse>

</j8583-config>

=== sylvaingir/j8583/src/test/resources/composites.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE j8583-config PUBLIC "-//J8583//DTD CONFIG 1.0//EN"
	"http://j8583.sourceforge.net/j8583.dtd">
<j8583-config>
<!-- This is a test config file -->

    <template type="100">
    	<field num="10" type="LLLVAR">
    		<field num="1" type="ALPHA" length="5">abcde</field>
    		<field num="2" type="LLVAR">llvar</field>
    		<field num="3" type="NUMERIC" length="5">12345</field>
    		<field num="4" type="ALPHA" length="1">X</field>
    	</field>
    </template>

    <template type="101">
    	<field num="10" type="LLLVAR">
            <field num="1" type="ALPHA" length="5">fghij</field>
    		<field num="2" type="LLVAR">
                <field num="1" type="ALPHA" length="2">KL</field>
                <field num="2" type="ALPHA" length="2">mn</field>
                <field num="3" type="LLVAR">
                    <field num="1" type="ALPHA" length="3">123</field>
                    <field num="2" type="ALPHA" length="2">45</field>
                </field>
            </field>
    		<field num="3" type="NUMERIC" length="5">67890</field>
    		<field num="4" type="ALPHA" length="1">Y</field>
    	</field>
    </template>

    <template type="102" extends="101">
        <field num="12" type="LLLVAR">
            <field num="1" type="ALPHA" length="5">fghij</field>
            <field num="2" type="LLVAR">
                <field num="1" type="ALPHA" length="2">KL</field>
                <field num="2" type="ALPHA" length="2">mn</field>
                <field num="3" type="LLVAR">
                    <field num="1" type="ALPHA" length="3">123</field>
                    <field num="2" type="ALPHA" length="2">45</field>
                </field>
            </field>
            <field num="3" type="NUMERIC" length="5">67890</field>
            <field num="4" type="ALPHA" length="1">Y</field>
        </field>
    </template>

    <parse type="100">
        <field num="10" type="LLLVAR">
            <field num="1" type="ALPHA" length="5" />
            <field num="2" type="LLVAR"/>
            <field num="3" type="NUMERIC" length="5" />
            <field num="4" type="ALPHA" length="1" />
        </field>
    </parse>

    <parse type="101">
        <field num="10" type="LLLVAR">
            <field num="1" type="ALPHA" length="5" />
            <field num="2" type="LLVAR">
                <field num="1" type="ALPHA" length="2" />
                <field num="2" type="ALPHA" length="2" />
                <field num="3" type="LLVAR">
                    <field num="1" type="ALPHA" length="3" />
                    <field num="2" type="ALPHA" length="2" />
                </field>
            </field>
            <field num="4" type="ALPHA" length="1" />
        </field>
    </parse>

</j8583-config>

=== sylvaingir/j8583/src/test/resources/bin_ascii.conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE j8583-config PUBLIC "-//J8583//DTD CONFIG 1.0//EN"
	"http://j8583.sourceforge.net/j8583.dtd">
<j8583-config>
    <parse type="100">
	    <field num="2" type="LLVAR" />
        <field num="3" type="ALPHA" length="6" />
        <field num="4" type="ALPHA" length="12" />
        <field num="6" type="ALPHA" length="12" />
        <field num="7" type="ALPHA" length="10" />
        <field num="10" type="ALPHA" length="8" />
        <field num="11" type="ALPHA" length="6" />
        <field num="12" type="ALPHA" length="6" />
        <field num="13" type="ALPHA" length="4" />
        <field num="15" type="ALPHA" length="4" />
        <field num="16" type="ALPHA" length="4" />
        <field num="18" type="ALPHA" length="4" />
        <field num="22" type="ALPHA" length="3" />
        <field num="32" type="LLVAR"/>
        <field num="37" type="ALPHA" length="12" />
        <field num="41" type="ALPHA" length="8" />
        <field num="42" type="ALPHA" length="15" />
        <field num="43" type="ALPHA" length="40" />
        <field num="48" type="LLVAR" />
        <field num="49" type="ALPHA" length="3" />
        <field num="51" type="ALPHA" length="3" />
        <field num="61" type="LLLVAR" />
    </parse>
    <parse type="810">
        <field num="7" type="DATE10" />
        <field num="11" type="ALPHA" length="6" />
        <field num="37" type="ALPHA" length="12" />
        <field num="39" type="ALPHA" length="2" />
        <field num="53" type="LLLVAR"  />
        <field num="70" type="ALPHA" length="3" />
    </parse>
</j8583-config>
